### ISSUE TITLE
NoMethodError: undefined method `coerce' for nil:NilClass

### ISSUE THREAD

**Issue by asppsa** [ginjo/rfm#16]
Hi there,

I'm using ginjo-rfm 2.1 at the moment and it works well.  I thought I would try upgrading to 3.0.4, but when I did a `find` on a model object I got the following:

~~~
NoMethodError: undefined method `coerce' for nil:NilClass
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/metadata/datum.rb:40:in `handler_callback'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:288:in `run_callback'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:267:in `receive_end_element'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:644:in `_end_element'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:717:in `sax_parse'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:717:in `block in run_parser'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:717:in `open'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:717:in `run_parser'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:482:in `build'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:475:in `build'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/sax_parser.rb:102:in `parse'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/utilities/connection.rb:80:in `parse'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/layout.rb:324:in `get_records'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/layout.rb:232:in `find'
	from /home/asp/.rvm/gems/ruby-2.1.2/gems/ginjo-rfm-3.0.4/lib/rfm/base.rb:107:in `find'
~~~

This was using the ox parser, but I also tried with the Nokogiri parser and got the same problem (albeit with a slightly different stack trace), and I've also tried using bleeding-edge git.  Unfortunately I am unable to post the data here that caused the issue as it contains sensitive private information.  If necessary though, I can try to make an anonymised version.

The issue seems to arise because the `Rfm::Metadata::Datum` object that raises the error only has one attribute, `name`.  As a result, the code in `Cursor#clean_member` overwrites the datum's `attributes` hash with just the value of `name`.   I will make a pull request with a suggested fix, but I don't really understand the code so I'm not sure if my approach makes any sense. 

Cheers.

**Comment by asppsa** [comment]
Sorry for never getting back to you on this.  For the record, although I never got around to verifying this, the example XML came direct to ruby from FileMaker, but I was using Rfm's `log_responses` flag to get the XML.   I had an unverified suspicion that perhaps that logger was reconstructing the XML in order to log it.  Anyway, lots of other things got in the way, so we decided just to stay with 2.1.

However, I've at last had time to come back to this & it seems that with the latest release of Rfm and a couple of tweaks, all my tests are now passing!  As such, I am closing this.  Thank you again for all your excellent work on this gem.

**Comment by ginjo** [comment]
@asppsa, glad it's working for you! I seem to recall that grabbing xml from the log output was problematic for some reason. Also from my own experience, Rails log output is often distorted, especially for large strings of text. Not sure if that's a Rails thing, or if I'm unwittingly breaking every server I build  :grin:
