### ISSUE TITLE
Rails-2.0: Credentials

### ISSUE THREAD

**Issue by chmich** [ginjo/rfm#43]
Hi Wiliam, 

is there a way to store the FileMaker-Password, which is currently in rfm.yml in the newly introduced credententials.yml.enc?

Best Regards and many Thanks!
Christian

**Comment by hazi** [comment]
rfm.yml is available in ERB

```yaml
:ssl:       true
:port:      443
:timeout:   60
:database_name:
  :host: example.com
  :account_name: user
  :password: <%= Rails.application.credentials.filemaker_user_password %>
  :database: database
```

**Comment by chmich** [comment]
Many thanks for the fast reply!
Thats what i seached for!
